name: coder
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  percent_indicator: ^1.0.14
  flutter_icons: ^0.1.3
  simple_coverflow: ^0.0.8
  flutter_swiper: ^1.1.5
  auto_size_text: ^1.1.2
  localstorage: ^2.0.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
  assets:
    - assets/1.jpg
    - assets/icons/js.png
    - assets/icons/py.png
    - assets/icons/java.png
    - assets/icons/dart.png

  fonts:

    - family: SF
      fonts:
        - asset: assets/fonts/sf/SF-Pro-Display-Medium.otf